---
- name: Run a terminal command to show hidden files
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: YES
    state: present
  notify:
    - "{{ finder_show_hidden_files_handler_name }}"
...
