---
- name: Check for Brewfile.
  stat:
    path: "{{ homebrew_php_brewfile_dir }}/Brewfile"
  register: homebrew_php_brewfile

- name: Install from Brewfile.
  command: "brew bundle chdir={{ homebrew_php_brewfile_dir }}"
  when: homebrew_php_brewfile.stat.exists and homebrew_php_use_brewfile
...
