---
- name: Check for Brewfile.
  stat:
    path: "{{ homebrew_comms_brewfile_dir }}/Brewfile"
  register: homebrew_comms_brewfile

- name: Install from Brewfile.
  command: "brew bundle chdir={{ homebrew_comms_brewfile_dir }}"
  when: homebrew_comms_brewfile.stat.exists and homebrew_comms_use_brewfile
...
